---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-minio-env
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  MINIO_ROOT_USER: {{ .Values.minio.auth.accessKey | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.auth.secretKey | quote }}
  MINIO_ENDPOINT: {{ .Values.minio.service.apiPort | quote }}
  MINIO_DEFAULT_BUCKET: {{ .Values.minio.env.defaultBucket | quote }}
