apiVersion: v2
name: flts
description: A Helm chart for ML time series model training and inference with Superset frontend
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - analytics
  - machine-learning
  - kafka
  - superset
  - mlflow
home: https://github.com/harp-wing/FLTS
sources:
  - https://github.com/harp-wing/FLTS
maintainers:
  - name: Alexander Lange
    email: alexander.lange@nokia.com
dependencies: []
annotations:
  category: Analytics